service: coveo-slack-integration
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x  # could be changed to v14 (current LTS) or v16 (current Latest)
  environment:
functions:
  slackRedirectURI:
    handler: index.oauthHandler
    timeout: 12
    events:
      - http:
          path: slack/oauth_redirect
          method: get
      - http:
          path: slack/install
          method: get
          
  slack:
    handler: index.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
